# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment


# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  push:
    branches:
      - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deployStaging:
    # The type of runner that the job will run on
    name:  Deploy to Staging
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Resource Group rg-githubactions  with Azure ARM
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription   
          subscriptionId: 9d299f43-70f9-4a56-885e-11dcee96dca6
          region: Australia East
          template: ./arm-templates/resourcegroup.json
          deploymentName: rg-githubactions
     
      - name: Deploy Storage Account 
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup   
          resourceGroupName: rg-githubactions
          subscriptionId: 9d299f43-70f9-4a56-885e-11dcee96dca6
          template: ./arm-templates/storageaccount.json          
          parameters: 
            ./arm-templates/storageaccount.parameters.json
            storageAccountName=globostg002
            location="Australia East"
          deploymentMode: incremental

      - run: echo ${{ steps.storageAccountDeploy.outputs.BlobUri}}
      
